# Generated by Django 5.1.2 on 2024-11-03 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBesideTheImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='pictures/')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
