# Generated by Django 5.0 on 2024-08-23 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
        ('posts', '0002_postcontentextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTextPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
