# Generated by Django 5.1.2 on 2024-12-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0035_auto_20230822_2208_squashed_0036_auto_20240311_1028"),
        ("posts", "0006_galleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("text", models.TextField()),
                ("link", models.URLField()),
            ],
            bases=("cms.cmsplugin",),
        ),
    ]
